'use client'
import {useEffect,useMemo,useState} from 'react'
type Product={id:number;name:string;sku:string;barcode?:string|null;retail_price:string;wholesale_price:string;unit:string}; type CartLine=Product&{quantity:number}; type Shift={id:number;location:number;opening_cash:string;open:boolean}; type Sale={id:number;number:string;total:string}
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api'
export default function POS(){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[token,setToken]=useState(''),[query,setQuery]=useState(''),[products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<CartLine[]>([]),[locationId,setLocationId]=useState('1'),[shift,setShift]=useState<Shift|null>(null),[openingCash,setOpeningCash]=useState('0'),[customerWholesale,setCustomerWholesale]=useState(false),[payment,setPayment]=useState('CASH'),[message,setMessage]=useState(''),[lastSale,setLastSale]=useState<Sale|null>(null),[returnSaleId,setReturnSaleId]=useState('')
 useEffect(()=>{const t=localStorage.getItem('tokad_token');if(t)setToken(t)},[])
 useEffect(()=>{if(!token||!query.trim()){setProducts([]);return} const c=new AbortController();fetch(`${API}/products/?q=${encodeURIComponent(query)}`,{signal:c.signal,headers:{Authorization:`Token ${token}`}}).then(r=>r.ok?r.json():[]).then(setProducts).catch(()=>{});return()=>c.abort()},[query,token])
 useEffect(()=>{if(token)fetch(`${API}/shifts/`,{headers:{Authorization:`Token ${token}`}}).then(r=>r.ok?r.json():[]).then((x:Shift[])=>setShift(x.find(s=>s.open)||null)).catch(()=>{})},[token])
 const total=useMemo(()=>cart.reduce((s,p)=>s+Number(customerWholesale?p.wholesale_price:p.retail_price)*p.quantity,0),[cart,customerWholesale])
 async function login(){setMessage('Signing in…');const r=await fetch(`${API}/auth/token/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const d=await r.json();if(!r.ok)return setMessage(d.non_field_errors?.[0]||'Invalid credentials');localStorage.setItem('tokad_token',d.token);setToken(d.token);setPassword('');setMessage('Signed in.')}
 function logout(){localStorage.removeItem('tokad_token');setToken('');setShift(null);setCart([])}
 async function openShift(){const r=await fetch(`${API}/shifts/`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Token ${token}`},body:JSON.stringify({location_id:+locationId,opening_cash:openingCash})});const d=await r.json();if(!r.ok)return setMessage(d.detail||JSON.stringify(d));setShift(d);setMessage(`Shift #${d.id} opened.`)}
 async function closeShift(){if(!shift)return;const cash=window.prompt('Closing cash amount','0');if(cash===null)return;const r=await fetch(`${API}/shifts/${shift.id}/close/`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Token ${token}`},body:JSON.stringify({closing_cash:cash})});const d=await r.json();if(!r.ok)return setMessage(d.detail||JSON.stringify(d));setShift(null);setMessage('Shift closed.')}
 function add(p:Product){setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{...p,quantity:1}]})}
 function changeQty(id:number,d:number){setCart(c=>c.map(i=>i.id===id?{...i,quantity:i.quantity+d}:i).filter(i=>i.quantity>0))}
 async function checkout(){if(!shift||!cart.length)return;setMessage('Processing…');const r=await fetch(`${API}/sales/checkout/`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Token ${token}`,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({shift_id:shift.id,location_id:shift.location,items:cart.map(i=>({product_id:i.id,quantity:i.quantity})),payments:[{method:payment,amount:total.toFixed(2)}]})});const d=await r.json();if(!r.ok)return setMessage(d.detail||JSON.stringify(d));setLastSale(d);setCart([]);setMessage(`Sale ${d.number} completed.`)}
 async function printReceipt(id=lastSale?.id){if(!id)return;const r=await fetch(`${API}/sales/${id}/receipt/`,{headers:{Authorization:`Token ${token}`}}),d=await r.json();if(!r.ok)return setMessage(d.detail||'Receipt unavailable');const rows=d.items.map((i:any)=>`<tr><td>${i.name}</td><td>${i.quantity}</td><td>₦${i.line_total}</td></tr>`).join('');const payments=d.payments.map((p:any)=>`<div>${p.method}: ₦${p.amount}</div>`).join('');const w=window.open('','_blank','width=420,height=700');if(!w)return setMessage('Allow pop-ups to print receipts.');w.document.write(`<html><head><title>${d.sale_number}</title><style>body{font-family:monospace;width:300px;margin:auto}table{width:100%;font-size:12px}h1{text-align:center;font-size:18px}.total{font-weight:bold;font-size:16px}</style></head><body><h1>TOKAD MART</h1><div>Receipt: ${d.sale_number}</div><div>${new Date(d.created_at).toLocaleString()}</div><hr/><table>${rows}</table><hr/><div>Subtotal: ₦${d.subtotal}</div><div>Discount: ₦${d.discount}</div><div>Tax: ₦${d.tax}</div><div class='total'>TOTAL: ₦${d.total}</div><hr/>${payments}<p>Thank you.</p></body></html>`);w.document.close();w.focus();w.print()}
 async function doReturn(){const saleId=Number(returnSaleId);if(!saleId)return;const raw=window.prompt('Enter sale item ID and quantity as ID:QTY');if(!raw)return;const [id,q]=raw.split(':');const r=await fetch(`${API}/sales/${saleId}/return/`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Token ${token}`},body:JSON.stringify({items:[{sale_item_id:Number(id),quantity:q}],reason:'POS return'})});const d=await r.json();setMessage(r.ok?`Return ${d.number} created. Refund: ₦${d.total}`:d.detail||JSON.stringify(d))}
 if(!token)return <main style={{maxWidth:420,margin:'80px auto',padding:24,fontFamily:'system-ui'}}><h1>Tokad Mart POS</h1><p>Cashier sign in</p><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username" style={{width:'100%',padding:12,marginBottom:8}}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" style={{width:'100%',padding:12,marginBottom:8}}/><button onClick={login} style={{width:'100%',padding:14}}>Sign in</button><p>{message}</p></main>
 if(!shift)return <main style={{maxWidth:520,margin:'80px auto',padding:24,fontFamily:'system-ui'}}><h1>Tokad Mart POS</h1><p>No open cashier shift.</p><label>Location ID <input value={locationId} onChange={e=>setLocationId(e.target.value)}/></label><br/><label>Opening cash <input value={openingCash} onChange={e=>setOpeningCash(e.target.value)}/></label><button onClick={openShift} style={{display:'block',padding:14,marginTop:16}}>Open shift</button><button onClick={logout} style={{marginTop:12}}>Sign out</button><p>{message}</p></main>
 return <main style={{fontFamily:'system-ui',padding:24,maxWidth:1200,margin:'auto'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h1>Tokad Mart POS</h1><p>Shift #{shift.id} · Location #{shift.location}</p></div><div><button onClick={closeShift}>Close shift</button> <button onClick={logout}>Sign out</button></div></header><div style={{display:'grid',gridTemplateColumns:'1.4fr 1fr',gap:24}}><section><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Scan barcode or search product…" style={{width:'100%',padding:14,fontSize:18}}/>{products.map(p=><button key={p.id} onClick={()=>add(p)} style={{display:'block',width:'100%',padding:14,textAlign:'left',marginTop:8}}>{p.name} · {p.sku} · ₦{customerWholesale?p.wholesale_price:p.retail_price}</button>)}<label style={{display:'block',marginTop:16}}>Wholesale pricing <input type="checkbox" checked={customerWholesale} onChange={e=>setCustomerWholesale(e.target.checked)}/></label><hr/><h3>Returns</h3><input value={returnSaleId} onChange={e=>setReturnSaleId(e.target.value)} placeholder="Original sale ID"/><button onClick={doReturn}>Start return</button></section><aside><h2>Cart</h2>{cart.map(i=><div key={i.id} style={{display:'flex',justifyContent:'space-between',padding:8}}><span>{i.name} × {i.quantity} <button onClick={()=>changeQty(i.id,-1)}>-</button> <button onClick={()=>changeQty(i.id,1)}>+</button></span><span>₦{(Number(customerWholesale?i.wholesale_price:i.retail_price)*i.quantity).toFixed(2)}</span></div>)}<h2>₦{total.toFixed(2)}</h2><select value={payment} onChange={e=>setPayment(e.target.value)}><option>CASH</option><option>POS</option><option>TRANSFER</option></select><button disabled={!cart.length} onClick={checkout} style={{display:'block',width:'100%',padding:16,marginTop:12}}>Complete sale</button>{lastSale&&<><button onClick={()=>printReceipt()} style={{display:'block',width:'100%',padding:12,marginTop:8}}>Print receipt</button><button onClick={()=>printReceipt(lastSale.id)} style={{display:'block',width:'100%',padding:12,marginTop:8}}>Reprint last receipt</button></>}<p>{message}</p></aside></div></main>
}
