import { useEffect, useMemo, useState } from 'react'

type Product={id:number;name:string;sku:string;barcode?:string|null;retail_price:string;wholesale_price:string;unit:string}
type CartLine=Product & {quantity:number}

const API=process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api'

export default function POS(){
 const [query,setQuery]=useState(''); const [products,setProducts]=useState<Product[]>([]); const [cart,setCart]=useState<CartLine[]>([]); const [locationId,setLocationId]=useState('1'); const [shiftId,setShiftId]=useState(''); const [customerWholesale,setCustomerWholesale]=useState(false); const [payment,setPayment]=useState('CASH'); const [message,setMessage]=useState('');
 useEffect(()=>{ if(!query) return setProducts([]); const c=new AbortController(); fetch(`${API}/products/?q=${encodeURIComponent(query)}`,{signal:c.signal}).then(r=>r.json()).then(setProducts).catch(()=>{}); return()=>c.abort()},[query])
 const total=useMemo(()=>cart.reduce((s,p)=>s+Number(customerWholesale?p.wholesale_price:p.retail_price)*p.quantity,0),[cart,customerWholesale])
 function add(p:Product){setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{...p,quantity:1}]})}
 async function checkout(){setMessage('Processing…'); const key=crypto.randomUUID(); const r=await fetch(`${API}/sales/checkout/`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({shift_id:Number(shiftId),location_id:Number(locationId),items:cart.map(i=>({product_id:i.id,quantity:i.quantity})),payments:[{method:payment,amount:total.toFixed(2)}]})}); const d=await r.json(); if(!r.ok)return setMessage(d.detail||JSON.stringify(d)); setMessage(`Sale ${d.number} completed`);setCart([])}
 return <main style={{fontFamily:'system-ui',padding:24,maxWidth:1200,margin:'auto'}}><h1>Tokad Mart POS</h1><p>Transactional checkout</p><div style={{display:'grid',gridTemplateColumns:'1.4fr 1fr',gap:24}}><section><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Scan barcode or search product…" style={{width:'100%',padding:14,fontSize:18}}/>{products.map(p=><button key={p.id} onClick={()=>add(p)} style={{display:'block',width:'100%',padding:14,textAlign:'left',marginTop:8}}>{p.name} · {p.sku} · ₦{customerWholesale?p.wholesale_price:p.retail_price}</button>)}<label>Wholesale customer <input type="checkbox" checked={customerWholesale} onChange={e=>setCustomerWholesale(e.target.checked)}/></label></section><aside><h2>Cart</h2>{cart.map(i=><div key={i.id} style={{display:'flex',justifyContent:'space-between',padding:8}}><span>{i.name} × {i.quantity}</span><span>₦{(Number(customerWholesale?i.wholesale_price:i.retail_price)*i.quantity).toFixed(2)}</span></div>)}<h2>₦{total.toFixed(2)}</h2><input value={shiftId} onChange={e=>setShiftId(e.target.value)} placeholder="Cashier shift ID"/><select value={payment} onChange={e=>setPayment(e.target.value)}><option>CASH</option><option>POS</option><option>TRANSFER</option></select><button disabled={!cart.length||!shiftId} onClick={checkout} style={{display:'block',width:'100%',padding:16,marginTop:12}}>Complete sale</button><p>{message}</p></aside></div></main>
}
