from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='Customer',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=255)),('phone',models.CharField(blank=True,default='',max_length=32)),('email',models.EmailField(blank=True,default='',max_length=254)),('wholesale',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True))]),
      migrations.CreateModel(name='InventoryLocation',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120,unique=True)),('active',models.BooleanField(default=True))]),
      migrations.CreateModel(name='Product',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('sku',models.CharField(max_length=64,unique=True)),('barcode',models.CharField(blank=True,max_length=128,null=True,unique=True)),('name',models.CharField(max_length=255)),('unit',models.CharField(default='pcs',max_length=32)),('retail_price',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('wholesale_price',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))]),
      migrations.CreateModel(name='CashierShift',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('opening_cash',models.DecimalField(decimal_places=2,max_digits=14)),('closing_cash',models.DecimalField(blank=True,decimal_places=2,max_digits=14,null=True)),('opened_at',models.DateTimeField(auto_now_add=True)),('closed_at',models.DateTimeField(blank=True,null=True)),('open',models.BooleanField(default=True)),('location',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='commerce.inventorylocation')),('user',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='StockBalance',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.DecimalField(decimal_places=3,default=0,max_digits=14)),('reserved_quantity',models.DecimalField(decimal_places=3,default=0,max_digits=14)),('version',models.PositiveBigIntegerField(default=0)),('location',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='commerce.inventorylocation')),('product',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='commerce.product'))]),
      migrations.CreateModel(name='Sale',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('number',models.CharField(max_length=32,unique=True)),('subtotal',models.DecimalField(decimal_places=2,max_digits=14)),('discount',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('tax',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('total',models.DecimalField(decimal_places=2,max_digits=14)),('status',models.CharField(choices=[('COMPLETED','Completed'),('VOID','Void')],default='COMPLETED',max_length=16)),('idempotency_key',models.CharField(max_length=128,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('cashier',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL)),('customer',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,to='commerce.customer')),('location',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='commerce.inventorylocation')),('shift',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='commerce.cashiershift'))]),
      migrations.CreateModel(name='IdempotencyKey',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('key',models.CharField(max_length=128,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('response_sale',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='commerce.sale'))]),
      migrations.CreateModel(name='Payment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('method',models.CharField(choices=[('CASH','Cash'),('POS','Pos'),('TRANSFER','Transfer')],max_length=16)),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('reference',models.CharField(blank=True,default='',max_length=128)),('created_at',models.DateTimeField(auto_now_add=True)),('sale',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='payments',to='commerce.sale'))]),
      migrations.CreateModel(name='SaleItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.DecimalField(decimal_places=3,max_digits=14)),('unit_price',models.DecimalField(decimal_places=2,max_digits=14)),('discount',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('line_total',models.DecimalField(decimal_places=2,max_digits=14)),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='commerce.product')),('sale',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='items',to='commerce.sale'))]),
      migrations.CreateModel(name='StockMovement',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity_delta',models.DecimalField(decimal_places=3,max_digits=14)),('movement_type',models.CharField(choices=[('PURCHASE','Purchase'),('SALE','Sale'),('SALE_RETURN','Sale return'),('ADJUSTMENT','Adjustment')],max_length=32)),('reference',models.CharField(max_length=128)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL)),('location',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='commerce.inventorylocation')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='commerce.product'))]),
      migrations.AddConstraint(model_name='stockbalance',constraint=models.UniqueConstraint(fields=('product','location'),name='unique_stock_balance'))
    ]
