# Generated by Django 5.2.17 on 2026-08-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactional', '0002_alter_inventorymovement_reason_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='reason',
            field=models.CharField(choices=[('SALE', 'Sale'), ('RETURN', 'Return'), ('PURCHASE', 'Purchase'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('DAMAGE', 'Damage')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('COMPLETED', 'Completed'), ('PAYMENT_FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32),
        ),
    ]
