# Generated by Django 5.2.17 on 2026-08-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactional', '0007_payment_provider_metadata'),
        ('transactional', '0007_payment_refund'),
    ]

    operations = [
    ]
