# Generated by Django 5.2.17 on 2026-08-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactional', '0008_merge_20260815_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='posoperator',
            name='locations',
            field=models.ManyToManyField(related_name='operators', through='transactional.POSOperatorLocation', to='transactional.poslocation'),
        ),
        migrations.AddField(
            model_name='posoperator',
            name='terminals',
            field=models.ManyToManyField(related_name='operators', through='transactional.POSOperatorTerminal', to='transactional.posterminal'),
        ),
        migrations.AlterField(
            model_name='paymentrefund',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='REQUESTED', max_length=32),
        ),
    ]
